### ISSUE TITLE
NoMethodError when using Apache 2 with Passenger

### ISSUE THREAD

**Issue by jackietheripper** [standardnotes/web#174]
#Hi,

Im am getting the following error, when trying to publish the app via Passenger:

```
Started GET "/notes/assets/compiled.self-83a31ed0c429d85746b22f3320d8e559ca6735a66ffb1d5804b0782b60a54416.js?body=1" for 192.168.1.12 at 2017-12-15 14:27:50 +0100
Cannot render console from 192.168.1.12! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Started GET "/notes/" for 192.168.1.12 at 2017-12-15 14:30:57 +0100
Cannot render console from 192.168.1.12! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead. (called from <class:ApplicationController> at /home/jelko/standardnotes_web/app/controllers/application_controller.rb:6)
Processing by ApplicationController#frontend as HTML
Completed 500 Internal Server Error in 3ms
  
NoMethodError (undefined method `<<' for nil:NilClass):
  
app/controllers/application_controller.rb:25:in `set_app_domain'
app/controllers/application_controller.rb:11:in `frontend'
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (6.7ms)
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.9ms)
  Rendering /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (27.2ms)
```

The issue can be resolved when I comment out the line `@appDomain << ':' + request.port.to_s unless request.port.blank?` (Line 25) in app/web/controllers/application_controller.rb, but I think this is not a good permanent solution.

Best gegards,
Jelko

**Comment by mobitar** [comment]
This function is unused anyway, I was meaning to remove it. Fixed in https://github.com/standardnotes/web/commit/a52f61405d88f48d0f0febfc803a3e888c6bc02a
