### ISSUE TITLE
No route matches [POST] "/auth"

### ISSUE THREAD

**Issue by Bjornskjald** [standardnotes/web#202]
Full log:

```
ActionController::RoutingError (No route matches [POST] "/auth"):

actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack (2.0.5) lib/rack/deflater.rb:34:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
secure_headers (5.0.5) lib/secure_headers/middleware.rb:13:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

NameError: uninitialized constant Mime::HTML
        from /var/lib/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:58:in `acceptable_content_type?'
        from /var/lib/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:36:in `block in call'
        from /var/lib/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
        from /var/lib/gems/2.5.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
        from /var/lib/gems/2.5.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
        from /var/lib/gems/2.5.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:36:in `call_app'
        from /var/lib/gems/2.5.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `block in call'
        from /var/lib/gems/2.5.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `block in tagged'
        from /var/lib/gems/2.5.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
        from /var/lib/gems/2.5.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `tagged'
        from /var/lib/gems/2.5.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `call'
        from /var/lib/gems/2.5.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
        from /var/lib/gems/2.5.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/request_id.rb:25:in `call'
        from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
        from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
        from /var/lib/gems/2.5.0/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
        from /var/lib/gems/2.5.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
        from /var/lib/gems/2.5.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/static.rb:125:in `call'
        from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
        from /var/lib/gems/2.5.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
        from /var/lib/gems/2.5.0/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
        from /var/lib/gems/2.5.0/gems/secure_headers-5.0.5/lib/secure_headers/middleware.rb:13:in `call'
        from /var/lib/gems/2.5.0/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
        from /var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
        from /var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
        from /var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
        from /var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
        from /var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mobitar** [comment]
What didn't work? What's the log say?

**Comment by smartspacemonkey** [comment]
I have the ruby-server running on port 3000, but when trying to register in the app (port 3004), I get the following message in a pop up window: "A server error occurred while trying to register. Please try again."

In the console, I get: 
```
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://localhost:3004
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3004
Use Ctrl-C to stop
2018-12-03 22:44:55.728 [INFO ] Started GET "/" for **FILTERED** at 2018-12-03 22:44:55 -0500 (pid:15656)
2018-12-03 22:44:55.734 [INFO ] Processing by ApplicationController#app as HTML (pid:15656)
2018-12-03 22:44:55.737 [INFO ] Rendering application/app.html.erb (pid:15656)
2018-12-03 22:44:55.883 [INFO ] Rendered application/app.html.erb (145.8ms) (pid:15656)
2018-12-03 22:44:55.888 [INFO ] Completed 200 OK in 153ms (Views: 148.7ms) (pid:15656)
2018-12-03 22:44:55.979 [INFO ] Started GET "/assets/compiled.self-3e7b26b71d4e239a01e447e8b26776f35fb22b8d42eb6138065b79881934788d.js?body=1" for **FILTERED** at 2018-12-03 22:44:55 -0500 (pid:15656)
2018-12-03 22:44:55.981 [INFO ] Started GET "/assets/app-efd767c2dd71eb856a393c4e647cce6c8c273f53448dbb31a76ff8369251f78b.css" for **FILTERED** at 2018-12-03 22:44:55 -0500 (pid:15656)
2018-12-03 22:45:21.823 [INFO ] Started POST "/auth" for **FILTERED** at 2018-12-03 22:45:21 -0500 (pid:15656)
2018-12-03 22:45:21.824 [FATAL]  (pid:15656)
2018-12-03 22:45:21.824 [FATAL] ActionController::RoutingError (No route matches [POST] "/auth"): (pid:15656)
2018-12-03 22:45:21.825 [FATAL]  (pid:15656)
2018-12-03 22:45:21.825 [FATAL] actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack (2.0.5) lib/rack/deflater.rb:34:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
secure_headers (6.0.0) lib/secure_headers/middleware.rb:13:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread' (pid:15656)

```

**Comment by bryvin** [comment]
It looks like you are trying to connect to the wrong server for registering. The [ruby-server](https://github.com/standardfile/ruby-server) which you stated you started on port 3000 is the one you should use for the Server ip/url. 

The web app is only the client for the Standard File ruby-server.

Let us know if that's the case and if you have any issues.

**Comment by mobitar** [comment]
Right, you're trying to access `[POST] "/auth"` on port 3004, but that route lives on port 3000. When you're registering inside the app, click Advanced Settings, and make sure Sync Server Domain is set to "http://localhost:3000".

**Comment by smartspacemonkey** [comment]
Works fine now, thanks !

**Comment by ston3o** [comment]
Hello,

Don't work for me, even I set http://localhost:3000 as Sync Server Domain, I have this error : 

`A server error occurred while trying to register. Please try again.`

```
/app
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.6.3-p62), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
2019-08-29 14:58:21.402 [INFO ] Started GET "/" for **FILTERED** at 2019-08-29 14:58:21 +0000 (pid:9)
2019-08-29 14:58:21.403 [INFO ] Cannot render console from **FILTERED**! Allowed networks: **FILTERED**, ::1, **FILTERED**/**FILTERED** (pid:9)
2019-08-29 14:58:21.408 [INFO ] Processing by ApplicationController#app as HTML (pid:9)
2019-08-29 14:58:21.412 [INFO ] Rendering application/app.html.erb (pid:9)
2019-08-29 14:58:22.911 [INFO ] Rendered application/app.html.erb (1499.6ms) (pid:9)
2019-08-29 14:58:22.916 [INFO ] Completed 200 OK in 1508ms (Views: 1502.9ms) (pid:9)
2019-08-29 14:58:22.979 [INFO ] Started GET "/assets/compiled.self-50e9c81eaa615dceba8cf57d464a507b678aee79f74afa18ba89720eeaa8fb71.js?body=1" for **FILTERED** at 2019-08-29 14:58:22 +0000 (pid:9)
2019-08-29 14:58:22.980 [INFO ] Cannot render console from **FILTERED**! Allowed networks: **FILTERED**, ::1, **FILTERED**/**FILTERED** (pid:9)
2019-08-29 14:58:22.981 [INFO ] Started GET "/assets/app-34377db8ac0a66c61bb19e263ccfe7635b064e8e53adaa85092fd47795c20d92.css" for **FILTERED** at 2019-08-29 14:58:22 +0000 (pid:9)
2019-08-29 14:58:22.981 [INFO ] Cannot render console from **FILTERED**! Allowed networks: **FILTERED**, ::1, **FILTERED**/**FILTERED** (pid:9)
2019-08-29 14:58:31.783 [INFO ] Started POST "/auth" for **FILTERED** at 2019-08-29 14:58:31 +0000 (pid:9)
2019-08-29 14:58:31.783 [INFO ] Cannot render console from **FILTERED**! Allowed networks: **FILTERED**, ::1, **FILTERED**/**FILTERED** (pid:9)
2019-08-29 14:58:31.785 [FATAL]  (pid:9)
2019-08-29 14:58:31.785 [FATAL] ActionController::RoutingError (No route matches [POST] "/auth"): (pid:9)
2019-08-29 14:58:31.785 [FATAL]  (pid:9)
2019-08-29 14:58:31.785 [FATAL] actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack (2.0.5) lib/rack/deflater.rb:34:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
secure_headers (6.0.0) lib/secure_headers/middleware.rb:13:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread' (pid:9)
```

**Comment by mobitar** [comment]
What do you see when you open http://0.0.0.0:3000 in a browser?

**Comment by ston3o** [comment]
I see this : 

![](https://i.imgur.com/ghKKb8f.png)

**Comment by ston3o** [comment]
And here commands I executed : 

```bash
git clone https://github.com/standardnotes/web
docker build -t standardnotes .
docker run --name standardnotes -p 3000:3000 standardnotes
```

**Comment by ston3o** [comment]
Sorry, I found my problem.
I didn't understand I had to use [ruby-server repository](https://github.com/standardfile/ruby-server) too.
