### ISSUE TITLE
Private Server - Extension Mgr errors

### ISSUE THREAD

**Issue by Svarto** [standardnotes/web#221]
Hi Mobitar,

I decided to open an issue instead to easier be able to share my error logs, also in case others face the same problem we can have the conversation in one place.

I followed the instructions to self host and the standardnote/web works fine, the only problem is with the extension manager. The button is there, however when clicking on it I get an error, it looks like the application is not reading my entry into .env, as the address it is sending the GET request to is not matching what I put in the .env file.

Going manually into the folder I specify within the .env, i.e. standardnote/public/extensions/extensions-manager/dist/ I can see that the index.html file exists.

My .env file:
```
EXTENSIONS_MANAGER_LOCATION=extensions/extensions-manager/dist/index.html
BATCH_MANAGER_LOCATION=extensions/batch-manager/dist/index.min.html
```

Error.log
```
Started GET "/extensionmgr/dist/index.html" for lan-ip at 2018-08-07 06:15:34 +0200

ActionController::RoutingError (No route matches [GET] "/extensionmgr/dist/index.html"):

actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack (2.0.5) lib/rack/deflater.rb:34:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
secure_headers (5.0.5) lib/secure_headers/middleware.rb:13:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

NameError: uninitialized constant Mime::HTML
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/web-console-2.3.0/lib/web_console/middleware.rb:58:in `acceptable_content_type?'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/web-console-2.3.0/lib/web_console/middleware.rb:36:in `block in call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/actionpack-5.1.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/railties-5.1.0/lib/rails/rack/logger.rb:36:in `call_app'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `block in call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `block in tagged'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `tagged'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/actionpack-5.1.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/actionpack-5.1.0/lib/action_dispatch/middleware/request_id.rb:25:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/actionpack-5.1.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/actionpack-5.1.0/lib/action_dispatch/middleware/static.rb:125:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/secure_headers-5.0.5/lib/secure_headers/middleware.rb:13:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
        from /home/svarto/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mobitar** [comment]
Be sure to restart the server/application after you change the .env file.

If not, it might be that the installed Extensions is using the wrong
url. Try signing out and clearing all data, so that a new Extensions
instance is created based on the current url.

**Comment by Svarto** [comment]
> Be sure to restart the server/application after you change the .env file. If not, it might be that the installed Extensions is using the wrong url. Try signing out and clearing all data, so that a new Extensions instance is created based on the current url.

Tried both of these just now, the exact same error is repeated. Signed in through an incognito window just to make sure that no cookie or so was saved, have the same error. :(

**Comment by Svarto** [comment]
When I manually go to this address:

https://own-domain-standardnote.com/extensions/extensions-manager/dist/index.html

Then I correctly get displayed "Installed Extensions", somehow my server is not reading correctly my .env file and incorrectly send me to the wrong url (the error says it sends me to /extensionmgr/dist/index.html for some reason)...

**Comment by Svarto** [comment]
Just an update, I fixed it temporarily by just moving the install extensions to the URL that the standardnote/web tried to fetch the extensions from, i.e. public/extensionmgr/* and public/batch_mgr/*

**Comment by mobitar** [comment]
Ok cool. Sorry, still unclear from the details what the original issue could have been.
