### ISSUE TITLE
Dockerfile is broken 

### ISSUE THREAD

**Issue by alexkutsan** [standardnotes/web#397]
Unable to build release 3.3.1 branch using docker. 
```
git clone https://github.com/standardnotes/web
cd web
git checkout 3.3.1
docker build .
```
Output : 
```
▶ docker build .
Sending build context to Docker daemon  3.597MB
Step 1/11 : FROM ruby:alpine
 ---> 3304101ccbe9
Step 2/11 : RUN apk add --update --no-cache     alpine-sdk     nodejs     nodejs-npm     tzdata
 ---> Using cache
 ---> 970a34415ffe
Step 3/11 : WORKDIR /app/
 ---> Using cache
 ---> 1fc10a110621
Step 4/11 : COPY . /app/
 ---> eb7e92b4099c
Step 5/11 : RUN bundle install
 ---> Running in d03063862ab8
/usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /app/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
	from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
The command '/bin/sh -c bundle install' returned a non-zero code: 1

```

**Comment by johnny243** [comment]
Hey @alexkutsan, I couldn't reproduce your issue.

Could you please provide the following information:

- OS version
- Docker version

Thanks!

**Comment by alexkutsan** [comment]
Looks like it is my local issue on Nix OS with docker 18.09.7

Checked docker build with GitHub actions https://github.com/alexkutsan/standardnotes_web/actions/runs/84547151 it works
